name: Plan

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Download OPA
        run: curl --silent --output opa https://openpolicyagent.org/downloads/latest/opa_linux_amd64
      
      - name: Make OPA executable
        run: chmod +x ./opa
      
      - name: Terrraform init
        run: terraform init
      
      - name: Terraform plan
        run: terraform plan --out tfplan.binary
        
      - name: Plan to JSON
        run: terraform show -json tfplan.binary > tfplan.json
        
      - name: OPA eval
        run: opa eval --fail-defined --input tfplan.json --data policy/main.rego 'data.main.deny'
      
      
