name: Plan

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.0
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
          terraform_wrapper: false

      - name: Download OPA
        run: curl --silent --location --output opa https://openpolicyagent.org/downloads/latest/opa_linux_amd64_static

      - name: Make OPA executable
        run: chmod +x ./opa

      - name: Terraform init
        run: terraform init

      - name: Terraform format
        run: terraform fmt -check

      - name: Plan
        run: terraform plan --out tfplan.binary
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Plan to JSON
        run: terraform show -json tfplan.binary > tfplan.json

      - name: Remove binary plan
        run: rm tfplan.binary

      - name: OPA eval
        run: ./opa eval --format pretty --fail-defined --input tfplan.json --data policy/main.rego 'data.main.deny[x]'

      # OR download conftest and run tests:
      # conftest test tfplan.json
