name: Plan

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 0.15.5
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
          terraform_wrapper: false

      - name: Download OPA
        run: curl --silent --location --output opa https://openpolicyagent.org/downloads/latest/opa_linux_amd64_static

      - name: Make OPA executable
        run: chmod +x ./opa

      - name: Terraform init
        run: terraform init

      - name: Terraform format
        run: terraform fmt -check

      - name: Plan
        run: terraform plan --out tfplan.binary
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Plan to JSON
        run: terraform show -json tfplan.binary > tfplan.json

      - name: Remove binary plan
        run: rm tfplan.binary

      #- name: OPA eval
      #  run: ./opa eval --fail-defined --input tfplan.json --data policy/main.rego 'data.main.deny[x]'

      - name: Download conftest
        run: |
          curl -L -s -o conftest.tar.gz https://github.com/open-policy-agent/conftest/releases/download/v0.25.0/conftest_0.25.0_Linux_x86_64.tar.gz
          tar xzf conftest.tar.gz
          rm conftest.tar.gz
          chmod +x conftest

      - name: Conftest test
        run: ./conftest test tfplan.json


      # TODO: Needs update - download manually for now
      #- name: conftest test
      #  uses: instrumenta/conftest-action@master
      #  with:
      #    files: tfplan.json
